##------------------------------------------------------------------
##------SERVER CONFIGURATION----------------------------------------
##------------------------------------------------------------------
server:
  port: 8081
spring:
  application:
    name: gateway-api
  security:
    user:
      name: admin
      password: 12341234

##------------------------------------------------------------------
##------GATEWAY API CONFIGURATION-----------------------------------
##------------------------------------------------------------------
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: true
    registry-fetch-interval-seconds: 30
    service-url:
      defaultZone: http://admin:12341234@${eureka.instance.hostname}:${server.port}/eureka



##------------------------------------------------------------------
##------ZUUL ROUTING CONFIGURATION----------------------------------
##------------------------------------------------------------------
zuul:
  routes:
    user-service:
      path: /user-service/**
    property-service:
      path: /property-service/**
    renter-service:
      path: /renter-service/**
